# Generated by Django 5.0.2 on 2024-03-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edu_pupil',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='edu_pupil',
            name='student_id',
        ),
        migrations.AddField(
            model_name='edu_pupil',
            name='book_id',
            field=models.ManyToManyField(to='education.edu'),
        ),
        migrations.AddField(
            model_name='edu_pupil',
            name='student_id',
            field=models.ManyToManyField(to='education.pupil'),
        ),
    ]
